### ISSUE TITLE
Transproxy for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by SecUpwN** [isislovecruft/scripts#8]
Good morning @isislovecruft! Thank you very much for `transproxy.firewall.sh`, I've been trying to use it to anonymize all traffic on my computer running [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed). Would you please have a look if the [output](https://defuse.ca/b/NgvCxpHh) is correct? If you know of a better way to anonymize all traffic through Tor, let me know!

**Comment by isislovecruft** [comment]
Hey @SecUpwN,

I'm sorry, I found this issue too late and I think now your paste has expired.  Could you paste it again, or (better) put it in this ticket?

**Comment by SecUpwN** [comment]
Thanks for responding, @isislovecruft. I'm afraid that I don't have that logfile anymore. But I wondered if your script could be added to `torbrowser-launcher` to solve https://github.com/micahflee/torbrowser-launcher/issues/223?

**Comment by isislovecruft** [comment]
Hi! As [micahflee mentioned](https://github.com/micahflee/torbrowser-launcher/issues/223#issuecomment-231455476), torifying a user's entire computer via Tor Browser isn't really the purpose of Tor Browser.  Tor Browser is a special fork of Firefox which guarantees your anonymity in many more ways than simply transparently routing your traffic through Tor.  So not only is it not that application's job to toryify an entire machine, but doing so would be dangerous, since there's no guarantee that the user's other applications wouldn't deanonymise them in some other way.
